### ISSUE TITLE
Change Request: Standardize OperationId's of paths in OpenApi definitions of FSPIOP API.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/mojaloop-specification#78]
### **Table of Contents**

* [1. Preface](#1.-preface)
  * [1.1 Change Request Information](#1.1-change-request-information)
* [2. Problem Description](#2.-problem-description)
  * [2.1 Background](#2.1-background)
  * [2.2 Current Behaviour](#2.2-current-behaviour)
  * [2.3 Requested Behaviour](#2.3-requested-behaviour)
* [3 Proposed Solution Options](#3.-proposed-solution-options)

<h2 id="1.-preface">1. Preface</h2>
___

This section contains basic information regarding the change request.

<h4 id="1.1-change-request-information">1.1 Change Request Information</h4>

| Requested By | Kevin Leyow, Modusbox |
| Change Request Status | In review ☒  / Approved ☐ / Rejected ☐ |
| Approved/Rejected Date |   |

<h2 id="2.-problem-description">2. Problem Description</h2>
___

<h4 id="2.1-background">2.1 Background</h4>

The OpenApi definitions of v1.0 and v1.1 of the FSPIOP Specification has no standard naming scheme for operationID's. OperationID's are important for some framworks when routing paths. Some microservices deviate from the hosted definition

<h4 id="2.2-current-behaviour">2.2 Current Behaviour</h4>

Current definition has no standardized naming scheme for operation Id's

Example
```
    put:
      description: The callback `PUT /participants/{Type}/{ID}` (or `PUT /participants/{Type}/{ID}/{SubId}`) is used to inform the client of a successful result of the lookup, creation, or deletion of the FSP information related to the Party. If the FSP information is deleted, the fspId element should be empty; otherwise the element should include the FSP information for the Party.
      summary: Return participant information
      tags:
        - participants
      operationId: ParticipantsByTypeAndID3
                                   ^ No HTTP verb. Not very descriptive
```

```
    post:
      description: The HTTP request `POST /participants/{Type}/{ID}` (or `POST /participants/{Type}/{ID}/{SubId}`) is used to create information in the server regarding the provided identity, defined by `{Type}`, `{ID}`, and optionally `{SubId}` (for example, `POST /participants/MSISDN/123456789` or `POST /participants/BUSINESS/shoecompany/employee1`). An ExtensionList element has been added to this reqeust in version v1.1
      summary: Create participant information
      tags:
        - participants
      operationId: ParticipantsSubIdByTypeAndIDPost
                              ^ Example of a descriptive name. Describes path. Uses HTTP verb. 
```

<h4 id="2.3-requested-behaviour">2.3 Requested Behaviour</h4>

Operation Id's are updated.

<h2 id="3.-proposed-solution-options">3. Proposed Solution Options</h2>
___

Decide on naming scheme and update documents.
